### ISSUE TITLE
Roadmap to v1: Hand Tracking / Hand Controllers / Simulation

### ISSUE THREAD

**Issue by FejZa** [XRTK/XRTK-Core#645]
# XRTK - Mixed Reality Toolkit Backlog

This backlog item is tracking the progress of XRTK's hand tracking and hand controllers implementation and should for one help to keep track of the work that needs to be done and already was done. Input and contributions welcome.

## In Progress

- [ ] https://github.com/XRTK/XRTK-Core/pull/552 Hand input gestures and interaction

## Planned

- [ ] Rename `HandBoundsMode.Hand | .Fingers` to `HandBoundsLOD.Low | .High`
- [ ] Allow mapping input actions to tracked hand poses
- [ ] Implement hand pose recorder utility
- [ ] Ultraleap (Leap Motion) support
- [ ] Hand Near Pointer refactor / enhancement
- [ ] Hand Tracking Mesh Visualization
- [ ] Hand Controller Visualization Refactor

## Done

- [x] https://github.com/XRTK/XRTK-Core/pull/216 Hand Tracking Base
- [x] https://github.com/XRTK/XRTK-Core/pull/216 Controller Simulation Base
