### ISSUE TITLE
Documentation checklist - 0.2 release

### ISSUE THREAD

**Issue by SimonDarksideJ** [XRTK/XRTK-Core#670]
# XRTK - Mixed Reality Toolkit Feature Request

Documentation review required for 0.2 release:

- [X] Getting started
- [X] Installation
- [X] FAQ for common runtime queries
- [ ] API docs review (autogen)
- [X] Examples documentation
- [X] Docs per platform (contained in \Documentation~ folder)

To follow Release:
- [ ] First project guide
- [ ] High level architecture guide (XRTK, Services, implementations, events and input)
